### ISSUE TITLE
Orthographic Error

### ISSUE THREAD

**Issue by sirpythagoras** [blackbatman56/blackbatman56.github.io#1]
Dear Sir, 

I am writing to you to inform you of an orthographic error that you have made on your html apparatus. For you see, it appears you have misspelled the word "one." I realize that this is a minor mistake, but I implore you to fix this travesty; doing so will better the lives of many across the globe. Additionally, since it is so minor, you shall be able to complete the task apace, as the old French put it.

I greatly thank you for your time and I am sure that you will not let all the poor people of the world down.

Toodle-oo!

**Comment by blackbatman56** [comment]
fixed it
